import 'package:EUIES_Web/Core/Widgets/webheadbar.dart';
import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(backgroundColor: Colors.white,
      body: SingleChildScrollView(
        child: Column(
            children: [Container(),
            const SizedBox(height: 100,),
            const Image(
            image: AssetImage("assets/images/studyineurope.png"),
            width: double.infinity,
          ),
            Container(
                decoration: BoxDecoration(color: Colors.white,),
                height: 200.0,
                width: double.infinity,
                child:
                Padding(
                  padding: const EdgeInsets.all(20.0),
                  child: Column(crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.start,
                    children: const [
                      Text('SERVICES', style: TextStyle(color: Colors.red, fontSize: 16),),
                      SizedBox(height: 15,),
                      Text('Our Dedicated Services', style: TextStyle(color: Colors.black, fontSize: 28, fontWeight: FontWeight.bold),),
                      SizedBox(height: 15,),
                      Text('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore.',
                        style: TextStyle(color: Colors.black, fontSize: 16,),textAlign: TextAlign.center,),
                      Text('________', style: TextStyle(color: Colors.red, fontSize: 20, fontWeight: FontWeight.bold),),
                    ],
                  ),
                ),
              ),
              SingleChildScrollView(scrollDirection: Axis.horizontal,
                child: Padding(
                  padding: const EdgeInsets.all(20.0),
                  child: Row(
                    children: [Container(),
                      ClipRRect(borderRadius: BorderRadius.circular(15),
                        child: Container(decoration: BoxDecoration(border: Border.all(color: Colors.blue, width: 1), color: Colors.white, borderRadius: BorderRadius.circular(15),),
                          height: 550,
                          width: 400,
                            child: Column(crossAxisAlignment: CrossAxisAlignment.start,
                                children: [Container(),
                              const Image(
                                image: AssetImage("assets/images/flag.png"),
                              ),
                                  SizedBox(height: 15,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('Study Abroad', style: TextStyle(color: Colors.black, fontSize: 20, fontWeight: FontWeight.bold),),
                                  ),
                                  SizedBox(height: 8,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('We provide expert services for students to fulfill their dreams of obtaining foreign education. Our students are placed all around the globe and we are proud to have helped students get admitted into top universities in destinations such as USA, Europe, Australia and more.',
                                      style: TextStyle(color: Colors.black, fontSize: 20,), softWrap: true,),
                                  ),
                            ],
                            ),
                          ),
                      ),
                      SizedBox(width: 20,),
                      ClipRRect(borderRadius: BorderRadius.circular(15),
                        child: Container(decoration: BoxDecoration(border: Border.all(color: Colors.blue, width: 1), color: Colors.white, borderRadius: BorderRadius.circular(15),),
                          height: 550,
                          width: 400,
                            child: Column(crossAxisAlignment: CrossAxisAlignment.start,
                                children: [Container(),
                              const Image(
                                image: AssetImage("assets/images/flag.png"),
                              ),
                                  SizedBox(height: 15,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('Study Abroad', style: TextStyle(color: Colors.black, fontSize: 20, fontWeight: FontWeight.bold),),
                                  ),
                                  SizedBox(height: 8,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('We provide expert services for students to fulfill their dreams of obtaining foreign education. Our students are placed all around the globe and we are proud to have helped students get admitted into top universities in destinations such as USA, Europe, Australia and more.',
                                      style: TextStyle(color: Colors.black, fontSize: 20,), softWrap: true,),
                                  ),
                            ],
                            ),
                          ),
                      ),
                      SizedBox(width: 20,),
                      ClipRRect(borderRadius: BorderRadius.circular(15),
                        child: Container(decoration: BoxDecoration(border: Border.all(color: Colors.blue, width: 1), color: Colors.white, borderRadius: BorderRadius.circular(15),),
                          height: 550,
                          width: 400,
                            child: Column(crossAxisAlignment: CrossAxisAlignment.start,
                                children: [Container(),
                              const Image(
                                image: AssetImage("assets/images/flag.png"),
                              ),
                                  SizedBox(height: 15,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('Study Abroad', style: TextStyle(color: Colors.black, fontSize: 20, fontWeight: FontWeight.bold),),
                                  ),
                                  SizedBox(height: 8,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('We provide expert services for students to fulfill their dreams of obtaining foreign education. Our students are placed all around the globe and we are proud to have helped students get admitted into top universities in destinations such as USA, Europe, Australia and more.',
                                      style: TextStyle(color: Colors.black, fontSize: 20,), softWrap: true,),
                                  ),
                            ],
                            ),
                          ),
                      ),
                      SizedBox(width: 20,),
                      ClipRRect(borderRadius: BorderRadius.circular(15),
                        child: Container(decoration: BoxDecoration(border: Border.all(color: Colors.blue, width: 1), color: Colors.white, borderRadius: BorderRadius.circular(15),),
                          height: 550,
                          width: 400,
                            child: Column(crossAxisAlignment: CrossAxisAlignment.start,
                                children: [Container(),
                              const Image(
                                image: AssetImage("assets/images/flag.png"),
                              ),
                                  SizedBox(height: 15,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('Study Abroad', style: TextStyle(color: Colors.black, fontSize: 20, fontWeight: FontWeight.bold),),
                                  ),
                                  SizedBox(height: 8,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('We provide expert services for students to fulfill their dreams of obtaining foreign education. Our students are placed all around the globe and we are proud to have helped students get admitted into top universities in destinations such as USA, Europe, Australia and more.',
                                      style: TextStyle(color: Colors.black, fontSize: 20,), softWrap: true,),
                                  ),
                            ],
                            ),
                          ),
                      ),
                      SizedBox(width: 20,),
                      ClipRRect(borderRadius: BorderRadius.circular(15),
                        child: Container(decoration: BoxDecoration(border: Border.all(color: Colors.blue, width: 1), color: Colors.white, borderRadius: BorderRadius.circular(15),),
                          height: 550,
                          width: 400,
                            child: Column(crossAxisAlignment: CrossAxisAlignment.start,
                                children: [Container(),
                              const Image(
                                image: AssetImage("assets/images/flag.png"),
                              ),
                                  SizedBox(height: 15,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('Study Abroad', style: TextStyle(color: Colors.black, fontSize: 20, fontWeight: FontWeight.bold),),
                                  ),
                                  SizedBox(height: 8,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('We provide expert services for students to fulfill their dreams of obtaining foreign education. Our students are placed all around the globe and we are proud to have helped students get admitted into top universities in destinations such as USA, Europe, Australia and more.',
                                      style: TextStyle(color: Colors.black, fontSize: 20,), softWrap: true,),
                                  ),
                            ],
                            ),
                          ),
                      ),
                      SizedBox(width: 20,),
                      ClipRRect(borderRadius: BorderRadius.circular(15),
                        child: Container(decoration: BoxDecoration(border: Border.all(color: Colors.blue, width: 1), color: Colors.white, borderRadius: BorderRadius.circular(15),),
                          height: 550,
                          width: 400,
                            child: Column(crossAxisAlignment: CrossAxisAlignment.start,
                                children: [Container(),
                              const Image(
                                image: AssetImage("assets/images/flag.png"),
                              ),
                                  SizedBox(height: 15,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('Study Abroad', style: TextStyle(color: Colors.black, fontSize: 20, fontWeight: FontWeight.bold),),
                                  ),
                                  SizedBox(height: 8,),
                                  Padding(
                                    padding: const EdgeInsets.all(10.0),
                                    child: Text('We provide expert services for students to fulfill their dreams of obtaining foreign education. Our students are placed all around the globe and we are proud to have helped students get admitted into top universities in destinations such as USA, Europe, Australia and more.',
                                      style: TextStyle(color: Colors.black, fontSize: 20,), softWrap: true,),
                                  ),
                            ],
                            ),
                          ),
                      ),
                    ],
                  ),
                ),
              ),
        Column(
          children: [Container(),
            SizedBox(height: 50,),
            Text('___  ___  ___  ___', style: TextStyle(color: Colors.red, fontSize: 25, fontWeight: FontWeight.bold),),
            SizedBox(height: 50,),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Column(
                  children: [Container(),
                    const Image(height: 400,
                      image: AssetImage("assets/images/about1.png"),
                    ),
                        SizedBox(height:30,),
                        Text('ABOUT ALL OF US', style: TextStyle(color: Colors.red, fontSize: 20, fontWeight: FontWeight.bold),),
                        SizedBox(height:10,),
                        Text('The Fastest Way to Gain Success',
                          style: TextStyle(color: Colors.black, fontSize: 30, fontWeight: FontWeight.bold),),
                        SizedBox(height:10,),
                        Text('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore.',
                        style: TextStyle(color: Colors.black, fontSize: 20,),textAlign: TextAlign.center,),
              ],
              ),
            ),
            ],
        ),

              SizedBox(height: 50,),
              Container(decoration: BoxDecoration(color: Colors.lightBlue),
                height: 280,
                width: double.infinity,
                child: Column(crossAxisAlignment: CrossAxisAlignment.start,
                  children: [Container(),
                    Padding(
                      padding: const EdgeInsets.all(20.0),
                      child: Text('Study Abroad', style: TextStyle(color: Colors.white, fontSize: 30, fontWeight: FontWeight.bold),),
                    ),
                    SingleChildScrollView(scrollDirection: Axis.horizontal,
                      child: Row(
                        children: [
                          SizedBox(width: 20,),
                          const Image(
                            image: AssetImage("assets/images/german1.png"),
                            height: 150,
                          ),
                          SizedBox(width: 20,),
                          const Image(
                            image: AssetImage("assets/images/german1.png"),
                            height: 150,
                          ),
                          SizedBox(width: 20,),
                          const Image(
                            image: AssetImage("assets/images/german1.png"),
                            height: 150,
                          ),
                          SizedBox(width: 20,),
                          const Image(
                            image: AssetImage("assets/images/german1.png"),
                            height: 150,
                          ),
                          SizedBox(width: 20,),
                          const Image(
                            image: AssetImage("assets/images/german1.png"),
                            height: 150,
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              SizedBox(height: 50,),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Column(
                  children: [Container(),
                    const Image(height: 400,
                      image: AssetImage("assets/images/whatwedo.png"),
                    ),
                    SizedBox(height:30,),
                    Text('SEE WHAT WE DO', style: TextStyle(color: Colors.red, fontSize: 20, fontWeight: FontWeight.bold),),
                    SizedBox(height:10,),
                    Text('Information is the Main Point to be Successful',
                      style: TextStyle(color: Colors.black, fontSize: 30, fontWeight: FontWeight.bold),),
                    SizedBox(height:10,),
                    Text('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy ant extra eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diammi maxil voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clitaiai to ankasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Adasta na lorem ipsum dolor sit amet, consetetur sadipscing elitr.',
                      style: TextStyle(color: Colors.black, fontSize: 20,),textAlign: TextAlign.center,),
                  ],
                ),
              ),
              SizedBox(height: 100,),
              Container(decoration: BoxDecoration(color: Colors.lightBlue),
                height: 250,
                width: double.infinity,
                child: SingleChildScrollView(scrollDirection: Axis.horizontal,
                  child: Padding(
                    padding: const EdgeInsets.all(20.0),
                    child: Row(crossAxisAlignment: CrossAxisAlignment.start,
                      children: [Container(),
                        Column(crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('EUIES', style: TextStyle(color: Colors.white, fontSize: 30, fontWeight: FontWeight.bold),),
                            SizedBox(height: 20,),
                            Text('Lorem ipsum dolor sit.',
                              style: TextStyle(color: Colors.white, fontSize: 15,),),
                            SizedBox(height: 20,),
                            Text('Contact:',
                              style: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),),
                            SizedBox(height: 15,),
                            Text('Phone: 17262546',
                              style: TextStyle(color: Colors.white, fontSize: 18,),),
                            SizedBox(height: 15,),
                            Text('Email: contact@euies.com',
                              style: TextStyle(color: Colors.white, fontSize: 18,),),
                          ],
                        ),
                        SizedBox(width: 60,),
                        Column(crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('Quick Links', style: TextStyle(color: Colors.white, fontSize: 30, fontWeight: FontWeight.bold),),
                            SizedBox(height: 20,),
                            Text('Contact Us:',
                              style: TextStyle(color: Colors.white, fontSize: 20,),),
                            SizedBox(height: 20,),
                            Text('Services:',
                              style: TextStyle(color: Colors.white, fontSize: 20,),),
                            SizedBox(height: 20,),
                            Text('Get A Quote',
                              style: TextStyle(color: Colors.white, fontSize: 20,),),
                          ],
                        ),
                        SizedBox(width: 60,),
                        Column(crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('Help Us', style: TextStyle(color: Colors.white, fontSize: 30, fontWeight: FontWeight.bold),),
                            SizedBox(height: 20,),
                            Text('About Us:',
                              style: TextStyle(color: Colors.white, fontSize: 20,),),
                            SizedBox(height: 20,),
                            Text('Help Center:',
                              style: TextStyle(color: Colors.white, fontSize: 20,),),
                            SizedBox(height: 20,),
                            Text('Feedback',
                              style: TextStyle(color: Colors.white, fontSize: 20,),),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
        ],
        ),
      ),
    );
  }
}
